### ISSUE TITLE
Consider testing on OS X as well as Linux on Travis CI

### ISSUE THREAD

**Issue by yurrriq** [lfe/docs#116]
https://docs.travis-ci.com/user/multi-os/

```yaml
os:
  - linux
  - osx
```

Related: #114

**Comment by yurrriq** [comment]
Sounds like there are some issues with Erlang on OS X on Travis: https://github.com/travis-ci/travis-ci/issues/2315

**Comment by yurrriq** [comment]
Fwiw I've had success with Nix on Travis and would be willing to set it up for this project if automated OS X testing is desirable.

**Comment by prertik** [comment]
I think @yurrriq should go for it as Erlang is not supported by Travis and there isn't work around unless Travis is hacked. What say @oubiwann?

**Comment by oubiwann** [comment]
we're going to be ditching the docs site, its generation with Ruby tools, etc.
