### ISSUE TITLE
Documentations/LFE book

### ISSUE THREAD

**Issue by prertik** [lfe/docs#119]
**The problem is there isn't enough documentations for LFE**. [http://docs.lfe.io/current/index.html](http://docs.lfe.io/current/index.html) contains different resources link but those links are either incomplete or outdated. There are less resources to learn how to use Erlang/OTP properly using LFE. 

> The major problem Erlang Community faces is proper documentation.

 Elixir fixed this problem with the best documentation in their website: [https://elixir-lang.org/getting-started/introduction.html](https://elixir-lang.org/getting-started/introduction.html) and books. LFE should however follow the approach done by Rust language [https://doc.rust-lang.org/book/](https://doc.rust-lang.org/book/) which is create a new project for creating a book which documents the language properly and would provide a better understanding of the LFE and show idiomatic ways to program LFE. The project should do: 

1. Give a proper understanding of Lisp-1 and Lisp-2
2. Demonstrate how Lispers can start programming in LFE.
3. Give a beginner introduction to ways of Lisp to non-lispers.
4. Demonstrate how to use Erlang features properly.
5. Demonstrate interoperability with Erlang and Elixir by using Cowboy and mix for small fun projects.
6. Demonstrate hot-code reloading, gen_server, supervisor, agent, creating umbrella apps, nodes and using macros "**The ultimate Lisp power**" to enhance the language.

(P.S. [http://docs.lfe.io/dev/](http://docs.lfe.io/dev/) looks promising. The question is can it fix this issue.)

**Comment by oubiwann** [comment]
Yeah, this is definitely a problem. The new dev site is really just the housing -- now the house needs to be filled.

**Comment by prertik** [comment]
I guess new project should be assigned for this. So, everyone can contribute a chapter or an example to the book/resources.

**Comment by oubiwann** [comment]
No, that's not necessary -- lfe/docs is the home for exactly that. My meaning above was simply that the version of the docs that is available at the URL http://docs.lfe.io/dev/ is a shell which provides the UI; the work on creating the new content has not been done yet, but needs to be.

To be clear:

* The dev version of the site currently only implements styling conventions, themes, widgets to be used, etc.
* It also establishes a convention for generating multiple versions of the docs and displaying these on the site appropriately
 * However, this UI work is only the smallest portion of what is actually covered in this repo

For the full list of topics covered in this repo, be sure to look at the tickets ... that being said, there are 59 open tickets and 49 closed ones, so there's a lot to absorb. This is made easier for new-comers by the manner in which the tickets are organized:
 * Release (most general; highest level of organization)
 * Epics (each release has one or more Epics)
 * Features & Tasks (each Epic has one or more of these;also,  a Feature is sometimes broken down into Tasks)

Example:
 * Release: v3.1 of the site - https://github.com/lfe/docs/issues/95

Epics are linked there, and each epic, in turn, has links to features, tasks, etc.

Note that when using Github in my browser, for whatever reason, I have to refresh the page each time I click one of those links; if I don't, then sometimes the ticket page loads and there's no content (no ticket description, not bullet lists, no comments/updates, no links to other tickets). So, if you see a blank ticket page, be sure to do a force refresh (e.g., ctrl+shift+r).

**Comment by prertik** [comment]
Thanks @oubiwann. This answers my queries. I will surely help to make LFE better!
