### ISSUE TITLE
Provide a Riak client tutorial in LFE

### ISSUE THREAD

**Issue by oubiwann** [lfe/docs#19]
https://github.com/basho/riak-erlang-client

**Comment by arpunk** [comment]
The guys at billosys are working on the library wrappers and the documentation:

* http://billo.gitbooks.io/lfe-taste-of-riak/
* http://billo.gitbooks.io/lfe-little-riak-book/

**Comment by oubiwann** [comment]
@arpunk Yup -- I think we can safely close this, thanks to that work :-)
