### ISSUE TITLE
Missing list formatting in Processes Tutorial part 4

### ISSUE THREAD

**Issue by naufraghi** [lfe/docs#31]
[Tutorial: Lightweight Processes: 4 Process Communications ](http://docs.lfe.io/tutorials/processes/4.html)

> To demonstrate this, let's update our print-result function to do this: \* pattern match for a process id as well as a message \* write message about sending data to another process \* actually send that data to the other process

**Comment by oubiwann** [comment]
That content is going to be removed in favour of the LFE books ...
