### ISSUE TITLE
Devise a mechanism for versioning docs

### ISSUE THREAD

**Issue by oubiwann** [lfe/docs#38]
Part of the [Versioning Docs Epic](https://github.com/lfe/docs/issues/68)

**Comment by oubiwann** [comment]
Currently looking at the Github documentation site. I posted the following comment in another ticket, and it should be here too:

I've been looking at projects like Read The Docs (Sphinx-based, uses ReST instead of Markdown ... not good for us, but pretty good overall API docs site features) and I haven't yet found anything that really grabs me.

The Github Documentation site is actually the most impressive I've seen so far:
 * https://developer.github.com/v3/

They blogged about how they're now supporting versioned docs (which we will need) with the latest Jekyll and the release of their new site: [How GitHub uses GitHub to document GitHub](https://github.com/blog/1939-how-github-uses-github-to-document-github). They've open-sourced their site here:
 * https://github.com/github/developer.github.com

I'm going to try to get a copy of it running and see how we might adapt it for LFE. Our stuff is already in markdown (all the sites as well as all the Gitbooks), and we use Jekyll already for the docs site and the blog, so this might be the best place to start for now ...

**Comment by oubiwann** [comment]
The Github docs also have their enterprise offering versioned:
 * https://developer.github.com/enterprise/2.1/
 * https://developer.github.com/enterprise/2.0/
 * https://developer.github.com/enterprise/11.10.340/

**Comment by oubiwann** [comment]
For the past year I've been using a series of ``make`` targets for this using Slate and (more recently) lodox-generated API docs. That will work just fine for the LFE docs site.

**Comment by yurrriq** [comment]
We should link to your ticket on Lodox re: version and improve its support for it.

**Comment by oubiwann** [comment]
This will be for the entire set of docs that are generated for the docs.lfe.io site, so I'm not sure this applies?

For more context, check out the mockup here:
 * http://docs3.lfe.io/examples/prototype-landing.html

In particular, the top-nav has a "Docs" drop-down -- this has version numbers in it. On the live site, this will be the mechanism whereby users will look at previous releases of the complete docs.lfe.io site ...

There will be make targets that generate the site content, and after a release, we'll be able to copy the entire site content generated in the "regular" output dir (e.g., ``current``) to a release directory (e.g., ``1.1.0``).

**Comment by yurrriq** [comment]
I'm commenting on this one, instead of all of them. When reading comments on my phone earlier I misunderstood the scope of these issues. Thanks for clarifying.

**Comment by oubiwann** [comment]
Done.
