### ISSUE TITLE
Inventory all the existing content on docs.lfe.io

### ISSUE THREAD

**Issue by oubiwann** [lfe/docs#54]
Once we have this list of everything on docs.lfe.io, we can group it along the best possible lines  (allowing content to appear in more than one section when it makes sense).

Once the content is grouped, we can prioritise: which things should get highlighted? Which content should users be guided towards?

For the new docs2 site, we need to keep in mind simplicity: high light the top three things (for example) in each section, and then provide more full details after that. We need to keep in mind the pain of the current docs site:
 * key information is not highlighted
 * information is cluttered
 * information is not well organized
 * too many hidden jewels that no one finds
 * unclear versioning of content with LFE releases

Part of the [Planning Epic](https://github.com/lfe/docs/issues/64).

**Comment by oubiwann** [comment]
Resources identified (so far):
 * https://github.com/rvirding/lfe/blob/develop/doc/
 * https://github.com/rvirding/lfe/tree/develop/examples
 * http://blog.lfe.io/categories.html#tutorials-ref
 * http://docs.lfe.io/tutorials/processes/1.html
 * http://docs.lfe.io/tutorials/mnesia/1.html
 * http://docs.lfe.io/tutorials/counter-app/1.html
 * http://blog.lfe.io/tutorials/2015/05/24/1808-what-is-otp/
 * https://www.gitbook.com/book/lfe/sicp/details
 * https://www.gitbook.com/book/lfe/casting-spels/details
 * https://www.gitbook.com/book/lfe/quick-start/details
 * https://www.gitbook.com/book/lfe/tutorial/details
 * http://lfex.github.io/hyperpolyglot/
 * http://rosettacode.org/wiki/Category:LFE

**Comment by rvirding** [comment]
So the problem is not the lack of documentation, it is putting them all together in a decent way. :-)

**Comment by oubiwann** [comment]
Indeed! And the docs above aren't even the complete list! (I'll be adding more/up[dating that comment as I have time to do more digging).

I've been making steady progress on a solution, though. It's starting to turn into a fun problem and one that will be not painful to maintain over time.

**Comment by oubiwann** [comment]
Calling this one done.
