### ISSUE TITLE
Light Weight Processes Tutorial - Section 4 Process Communications

### ISSUE THREAD

**Issue by shrogers** [lfe/docs#57]
(defmodule messenger-back
 (export (print-result 0) (send-message 1)))

should be 

(defmodule messenger-back
 (export (print-result 0) (send-message 2)))

and 

 (: messenger-back send-message '"There was a terrible ghastly silence.")

should be

 (: messenger-back send-message (self) '"There was a terrible ghastly silence.")

**Comment by oubiwann** [comment]
Thanks!

**Comment by oubiwann** [comment]
We're going to be deprecating the LFE docs site in favour of the various LFE books and lfe.io/docs
