### ISSUE TITLE
Docs no longer publish in Jekyll 3.0

### ISSUE THREAD

**Issue by oubiwann** [lfe/docs#71]
I has a sad.

Since we published last to the docs site in December, Github has upgraded and I can no longer publish the docs. Trying to work this out now ...

**Comment by oubiwann** [comment]
Wow, nice going Github. Promising markup and syntax highlighting compatibility with their upgrade. Turns out they don't give a shit about Lisp. Working my way through the docs to fix the things that are now "broken" on Github gh-pages.

I'd really like to not use Github's pages in the new version of the docs.  I'll see if we can generate everything on our workstations and then push the generated HTML ourselves.

**Comment by oubiwann** [comment]
Oh, and the best part? The error for this is ... 

```
jekyll 3.1.2 | Error:  empty stack!
```

Yeah, that was awesome.

**Comment by oubiwann** [comment]
Building locally with ``jekyll build -VI`` was useful in addressing all of these issues.

**Comment by oubiwann** [comment]
Okay, just uploaded to Github with the latest fixes, and the pages successfully built on their servers.

The docs revamp is going to be a bigger project than planned ....

**Comment by yurrriq** [comment]
Guhhh... :+1: for generate and push.
