### ISSUE TITLE
Add LFE Code of Conduct

### ISSUE THREAD

**Issue by oubiwann** [lfe/docs#74]
Examples:
- Python: https://www.python.org/psf/codeofconduct/
- Ubuntu: http://www.ubuntu.com/about/about-ubuntu/conduct

**Comment by yurrriq** [comment]
:+1: to this. I'd be curious to hear feedback from those new to the community too. Maybe someone can write a blog post soliciting such feedback.

**Comment by rvirding** [comment]
Do we really have to do this? To have a CoC for the community? Is it our problem?

**Comment by yurrriq** [comment]
I think it's good to set a precedence in case of future issues, but also it can be welcoming to new users who might otherwise be wary.

**Comment by yurrriq** [comment]
This could be more of an umbrella document for both LFE proper and lfex, etc. It can also serve as a statement of purpose, so to speak.

**Comment by oubiwann** [comment]
@rvirding: I don't think we need it right away. The first time we have a community member on the list or IRC or Twitter, etc., say something terrible to someone, we'll need one (and pronto). Fortunately, we haven't needed that. Unfortunately, if we experience growth, a precipitating event will just become more likely. I'm sure there's a numbered Internet Rule for that :-/

That being said, we don't need to make a big deal about it (we just need to eventually have something we can point to) and we can make it nice and simple, like the Python one.

**Comment by oubiwann** [comment]
Do this in guidebook.
