### ISSUE TITLE
Publishing LFE Modules/Projects

### ISSUE THREAD

**Issue by oubiwann** [lfe/docs#80]
Provide docs for LFE users who need to learn how to do this.

Possible inspiration: 
- https://docs.python.org/3/distributing/index.html

**Comment by yurrriq** [comment]
Should we get LFE and the major lfex libs on Hex?

**Comment by oubiwann** [comment]
Dunno. I guess my view on that is "if someone wants to do that work, cool" ... but I'm not really interested in using the hex or mix tool chain(s).

What we've been doing in the LFE world so far is simply creating repos for LFE libs/otp apps with ``rebar.confg`` files and then using those from other projects. This will mostly be a guide for folks who have not created LFE projects before or not shared them with others. The sort of basic documentation we're currently missing. I expect it will also cover creating OTP releases and demonstrate how one uses a release or app from someone else in a project. So that would be a little more intermediate-level ...

**Comment by oubiwann** [comment]
Do this in guidebook instead.
