### ISSUE TITLE
Quickstart inconsistency around projects

### ISSUE THREAD

**Issue by tlicata** [lfe/docs#82]
At the very bottom of the first page of the LFE Quickstart (https://lfe.gitbooks.io/quick-start/content/1.html) under "Next Stop" it says "Next you'll learn how to create a new LFE project with just one command ...".  But, even though the next page (https://lfe.gitbooks.io/quick-start/content/2.html) is titled "Creating a New Project", all of its content is about the REPL.

I am confused because I was interested in creating a new project (possibly with rebar?) and including a list of dependencies, my build instructions, etc. and assumed the next page was going to be about that.  Is this a case of restructuring gone wrong or have I misinterpreted the meaning of "create a new LFE project"?

I later found this page: http://blog.lfe.io/tutorials/2016/03/25/0858-lfe-and-rebar3/, which seems geared towards people who know rebar, have an existing erlang project, and want to integrate lfe.

I guess I'm looking for the equivalent of `rails new`, or `npm init`, or `lein new`.  I see there's a `rebar3 new`, but I'm not sure how to make that work with LFE.

**Comment by yurrriq** [comment]
The docs are fairly scattered and often out of date now, so there are a few such inconsistencies. The blog post you linked has current information and `rebar3` is the recommended tool for LFE projects. It describes how to compile LFE source and run LFE tests in the context of a `rebar3` project. It is directed at people who have `rebar3` installed, but it's not necessarily for integrating LFE into existing Erlang projects. How could we clarify that last point in the post?

Much of the `rebar3` tooling for LFE (see: the [lfe-rebar3](https://github.com/lfe-rebar3) GitHub organization) is in flux too, but the compiler plugin, `lfe-compile`, is solid.

The `rebar3 new` command relies on templates and we haven't quite firmed up any "official" ones yet. I started collecting some [here](https://github.com/lfe-rebar3/templates), and @arpunk has some good ones [here](https://github.com/arpunk/rebar3_lfe_templates).

What would be the most helpful, in terms of documentation, templates, etc, for you and other newcomers? We're planning to revamp the docs and suggestions would be greatly appreciated.

Thanks for raising the issue.

/cc @oubiwann

**Comment by yurrriq** [comment]
Feel free to [join us on Slack](https://lfe-slack.herokuapp.com) to discuss documentation updates or whatever else. There's a #docs channel in there too. Otherwise there are generally people  #erlang-lisp on Freenode.

**Comment by tlicata** [comment]
> It is directed at people who have rebar3 installed, but it's not necessarily for integrating LFE into existing Erlang projects. How could we clarify that last point in the post?

It assumes I have an existing `rebar.config`, but I don't because I'm a n00b :)  So including the step to generate one would be nice (unless it's out of scope for such a tutorial).

> The rebar3 new command relies on templates and we haven't quite firmed up any "official" ones yet. I started collecting some here, and @arpunk has some good ones here.

Oh, very helpful, thanks.  I will check them out.

> What would be the most helpful, in terms of documentation, templates, etc, for you and other newcomers? We're planning to revamp the docs and suggestions would be greatly appreciated.

Well, I'd like a section in the Quick Start about creating a new rebar project.  I am new to LFE so I can't tell the forest from the trees, so maybe that's misguided, but it's what I'm currently longing for :).  It would also be nice if the existing references to creating a project could be removed or updated.  The one I mentioned above and also the LFE Modules page (https://lfe.gitbooks.io/quick-start/content/3.html) says "What does a project look like? Well, if you want to see a full project, be sure to checkout the lfetool Quick Start." but it just links to the current page.

Thanks for responding so quickly.  If I can help out with any of these things, let me know :)

**Comment by yurrriq** [comment]
I've reread it and totally understand the confusion. I'll work on getting a minimum viable version of the templates plugin going.

**Comment by rvirding** [comment]
I have had one thought. Could we include in the LFE release an example rebar.config template people could use? Something to get going with.

**Comment by tlicata** [comment]
FWIW, I was able to accomplish what I was after by following the instructions on [arpunk's templates]( https://github.com/arpunk/rebar3_lfe_templates), so thanks for mentioning them.

**Comment by yurrriq** [comment]
@tlicata: Great!

@rvirding: AFAIK, `rebar3` templates have to be in the `priv` dir of an installed (project local or globs) plugin, but I might be wrong. The last @oubiwann and I talked about it, we were thinking of maybe making a sort of no-op plugin that includes some templates. It may also be a good idea to include some in LFE itself and add a `make` target that installs them to `~/.config/rebar3/templates` or wherever they go. There's some discussion on an issue in lfe-rebar3/templates. I think I'm leaning more toward the `make` target approach, since the templates are most useful globally and a no-op plugin seems like a bit of a waste.

**Comment by tlicata** [comment]
For the record, I found the User Guide to have more in-depth info on setting up a development environment (see [here](http://docs.lfe.io/user-guide/intro/4.html)). However, it too it references `lfetool` which is [deprecated](https://github.com/lfex/lfetool) :(

**Comment by oubiwann** [comment]
Heads-up: I've created a new ticket to track the conversion of lfetool references to rebar3 best practices:
 * https://github.com/lfe/docs/issues/84

Closing this ticket, as the main concern (of generating a new project using rebar3) was figured out and the more general concern is being covered with specifics in issue #84.
