### ISSUE TITLE
[http://docs.lfe.io/community-details][blog] Duncan McGreggor ...

### ISSUE THREAD

**Issue by rprimus** [lfe/docs#83]
Sat Aug 20 12:36:03 BST 2016

[Duncan McGreggor's blog](http://technicae.cogitat.io/search/label/lfe) is failing with the following error:

```
Your request for http://technicae.cogitat.io/search/label/lfe could not be fulfilled, because the domain name technicae.cogitat.io could not be resolved.
```

Is there a new blog location?

**Comment by oubiwann** [comment]
I'm hoping to get to this today!

**Comment by oubiwann** [comment]
Also had to update the top-nav link.

Should be fixed now!

**Comment by rprimus** [comment]
Wed Aug 24 15:54:33 BST 2016

Didn't want to open a new issue:

The community tab (top navigation) on the following page:

http://docs.lfe.io/community-details.html

points to:
http://docs.lfe.io/community.html

which is a 404.

**Comment by oubiwann** [comment]
Yikes, it does indeed ...

/me wonders why that didn't show up in the git grep I did ...

Ah, it was right next to the old one. I just missed it.

Fixed and pushed!
